permalink: /:title/

#lang: "en"
#excerpt_separator: "\n\n\n"
#date_format: "%B %d, %Y"

url: "https://bytehuman.blog"
baseurl: ""

include:
  - assets
  - assets/css/unocss.css

kramdown:
  smart_quotes: ["lsquo", "rsquo", "quot", "quot"]